import type { Project, Style } from './types'

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Summer Vibes EP - Track 3',
    style: 'Modern Pop',
    status: 'complete',
    createdAt: '2026-05-01T10:30:00Z',
    updatedAt: '2026-05-01T11:45:00Z',
    vocalFile: 'vocal_track3.wav',
    stemFiles: ['drums.wav', 'bass.wav', 'synth.wav', 'keys.wav'],
    metrics: {
      lufs: -14.2,
      truePeak: -1.0,
      lra: 7.8,
      stereoWidth: 0.72,
      codecQc: 'pass',
    },
    outputUrl: '/mock/output-001.wav',
    abVersions: [
      { id: 'a', label: 'Version A – Balanced', url: '/mock/a.wav', isSelected: true },
      { id: 'b', label: 'Version B – Vocal Forward', url: '/mock/b.wav', isSelected: false },
    ],
    progress: [
      { id: 'upload', label: 'Upload', status: 'complete', timestamp: '2026-05-01T10:30:00Z' },
      { id: 'analysis', label: 'Analysis', status: 'complete', timestamp: '2026-05-01T10:32:00Z' },
      { id: 'mixing', label: 'Mixing', status: 'complete', timestamp: '2026-05-01T10:45:00Z' },
      { id: 'mastering', label: 'Mastering', status: 'complete', timestamp: '2026-05-01T11:15:00Z' },
      { id: 'qc', label: 'Quality Check', status: 'complete', timestamp: '2026-05-01T11:40:00Z' },
      { id: 'delivery', label: 'Delivery', status: 'complete', timestamp: '2026-05-01T11:45:00Z' },
    ],
  },
  {
    id: 'proj-002',
    name: 'Midnight Drive – Remix',
    style: 'Synthwave',
    status: 'mastering',
    createdAt: '2026-05-05T14:00:00Z',
    updatedAt: '2026-05-05T15:20:00Z',
    vocalFile: 'midnight_vocal.wav',
    stemFiles: ['retro_drums.wav', 'synth_lead.wav', 'bass_synth.wav'],
    metrics: {
      lufs: -13.8,
      truePeak: -0.8,
      lra: 6.5,
      stereoWidth: 0.85,
      codecQc: 'pending',
    },
    progress: [
      { id: 'upload', label: 'Upload', status: 'complete', timestamp: '2026-05-05T14:00:00Z' },
      { id: 'analysis', label: 'Analysis', status: 'complete', timestamp: '2026-05-05T14:03:00Z' },
      { id: 'mixing', label: 'Mixing', status: 'complete', timestamp: '2026-05-05T14:30:00Z' },
      { id: 'mastering', label: 'Mastering', status: 'active' },
      { id: 'qc', label: 'Quality Check', status: 'pending' },
      { id: 'delivery', label: 'Delivery', status: 'pending' },
    ],
  },
  {
    id: 'proj-003',
    name: 'Acoustic Session Vol.2',
    style: 'Acoustic',
    status: 'processing',
    createdAt: '2026-05-07T09:15:00Z',
    updatedAt: '2026-05-07T09:20:00Z',
    vocalFile: 'acoustic_vocal.wav',
    stemFiles: ['guitar.wav', 'strings.wav'],
    progress: [
      { id: 'upload', label: 'Upload', status: 'complete', timestamp: '2026-05-07T09:15:00Z' },
      { id: 'analysis', label: 'Analysis', status: 'active' },
      { id: 'mixing', label: 'Mixing', status: 'pending' },
      { id: 'mastering', label: 'Mastering', status: 'pending' },
      { id: 'qc', label: 'Quality Check', status: 'pending' },
      { id: 'delivery', label: 'Delivery', status: 'pending' },
    ],
  },
  {
    id: 'proj-004',
    name: 'Bass Drop – Club Edit',
    style: 'EDM',
    status: 'uploading',
    createdAt: '2026-05-08T08:00:00Z',
    updatedAt: '2026-05-08T08:00:00Z',
    vocalFile: 'club_vocal.wav',
    stemFiles: ['kick.wav', 'bass.wav', 'lead.wav', 'fx.wav', 'pad.wav'],
    progress: [
      { id: 'upload', label: 'Upload', status: 'active' },
      { id: 'analysis', label: 'Analysis', status: 'pending' },
      { id: 'mixing', label: 'Mixing', status: 'pending' },
      { id: 'mastering', label: 'Mastering', status: 'pending' },
      { id: 'qc', label: 'Quality Check', status: 'pending' },
      { id: 'delivery', label: 'Delivery', status: 'pending' },
    ],
  },
  {
    id: 'proj-005',
    name: 'Lo-Fi Study Beats',
    style: 'Lo-Fi Hip Hop',
    status: 'failed',
    createdAt: '2026-05-06T16:30:00Z',
    updatedAt: '2026-05-06T16:50:00Z',
    vocalFile: 'lofi_sample.wav',
    stemFiles: ['lofi_drums.wav', 'piano.wav'],
    progress: [
      { id: 'upload', label: 'Upload', status: 'complete', timestamp: '2026-05-06T16:30:00Z' },
      { id: 'analysis', label: 'Analysis', status: 'complete', timestamp: '2026-05-06T16:33:00Z' },
      { id: 'mixing', label: 'Mixing', status: 'failed' },
      { id: 'mastering', label: 'Mastering', status: 'pending' },
      { id: 'qc', label: 'Quality Check', status: 'pending' },
      { id: 'delivery', label: 'Delivery', status: 'pending' },
    ],
  },
]

export const mockStyles: Style[] = [
  {
    id: 'style-pop',
    name: 'Modern Pop',
    description: 'Clean, punchy pop production with radio-ready loudness and clarity.',
    genre: 'Pop',
    tags: ['radio-ready', 'clean', 'punchy', 'bright'],
  },
  {
    id: 'style-hiphop',
    name: 'Hip Hop / Trap',
    description: 'Hard-hitting 808s, crisp hi-hats, and vocal-forward mixing.',
    genre: 'Hip Hop',
    tags: ['808', 'trap', 'vocal-forward', 'hard-hitting'],
  },
  {
    id: 'style-edm',
    name: 'EDM / Electronic',
    description: 'Wide stereo field, heavy sidechain, festival-ready loudness.',
    genre: 'Electronic',
    tags: ['sidechain', 'wide', 'loud', 'festival'],
  },
  {
    id: 'style-rnb',
    name: 'R&B / Soul',
    description: 'Warm, lush mixes with smooth low end and silky vocal treatment.',
    genre: 'R&B',
    tags: ['warm', 'smooth', 'lush', 'vocal-focused'],
  },
  {
    id: 'style-rock',
    name: 'Rock / Alternative',
    description: 'Aggressive guitar tones, dynamic drums, and raw energy.',
    genre: 'Rock',
    tags: ['aggressive', 'dynamic', 'raw', 'guitar-driven'],
  },
  {
    id: 'style-acoustic',
    name: 'Acoustic / Folk',
    description: 'Natural, organic sound with minimal processing and wide dynamics.',
    genre: 'Acoustic',
    tags: ['natural', 'organic', 'dynamic', 'minimal'],
  },
  {
    id: 'style-synthwave',
    name: 'Synthwave / Retro',
    description: '80s-inspired analog warmth, lush reverbs, and nostalgic pads.',
    genre: 'Electronic',
    tags: ['retro', 'analog', '80s', 'warm'],
  },
  {
    id: 'style-lofi',
    name: 'Lo-Fi Hip Hop',
    description: 'Vinyl warmth, tape saturation, and relaxed beat processing.',
    genre: 'Lo-Fi',
    tags: ['vinyl', 'tape', 'chill', 'warm'],
  },
]
